name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *' # se ejecuta todos los días a las 12:00 UTC
  workflow_dispatch: # para que lo ejecutes manualmente también

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update log file
        run: |
          echo "Último commit: $(date)" > log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Commit automático del día $(date)" || echo "No hay cambios para commitear"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
